server.port=8081
#logging.level.root=info

#spring jpa config
#spring.jpa.database=MySQL
#spring.datasource.url=
#spring.datasource.username=
#spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true



