#端口号配置
server:
   port: 8081
   
spring:
#数据库连接配置
   datasource:
      url: jdbc:mysql://10.135.4.46:3306/im_cloud
      username: ims
      password: Symbol_RAcimdb_1218

#Mybatis配置
mybatis:
   type-aliases-package: com.im.BaseService.domain #扫描数据持久层对应的实体类 路径 Package级别
   mapper-locations: classpath:mapper/*.xml
   

# ----------------
# Orphan comments:
# ----------------
# Was at begin of line:14 :#
# Was at begin of line:16 :#mybatis 对应的.xml文件路径
# Was at begin of line:19 :#logging.level.root=info
# Was at begin of line:21 :#spring jpa config
# Was at begin of line:22 :#spring.jpa.database=MySQL
# Was at begin of line:23 :#spring.datasource.url=
# Was at begin of line:24 :#spring.datasource.username=
# Was at begin of line:25 :#spring.datasource.password=
# Was at begin of line:26 :#spring.jpa.hibernate.ddl-auto=update
# Was at begin of line:27 :#spring.jpa.show-sql=true